export const STOCK_TRACKER_SCRIPT = "StockTrader/bin/tracker.js"
export const STOCK_ANALYSER_SCRIPT = "StockTrader/bin/analyser.js"
export const STOCK_LOG_SCRIPT = "StockTrader/bin/log.js"
export const STOCK_TRADER_SCRIPT = "StockTrader/bin/trader.js"
export const STOCK_HUD_SCRIPT = "StockTrader/bin/hud.js"
export const STOCK_COORDINATOR_SCRIPT = "StockTrader/bin/coordinator.js"
