export const SCRIPT_WEAKEN = "cmd-weaken.js"
export const SCRIPT_HACK = "cmd-hack.js"
export const SCRIPT_GROW = "cmd-grow.js"
export const SCRIPT_WGWH_LOOP = "wgwh-loop.js"
export const SCRIPT_WGWH_STATUS = "wgwh-status.js"
export const SCRIPT_SERVER_STATUS = "server-status.js"
